kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-rds-config
  namespace: kubeflow
data:
  DB_NAME_PIPELINES: <<conf.rds.db_name.pipelines.conf>>
  DB_NAME_CACHE: <<conf.rds.db_name.cache.conf>>
  RDS_HOST: <<conf.rds.host.conf>>
  RDS_PORT: "<<conf.rds.port.conf>>"
