kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-rds-config
  namespace: kubeflow
data:
  DB_NAME_PIPELINES: <<__rds.db_name.pipelines__>>
  DB_NAME_CACHE: <<__rds.db_name.cache__>>
  DB_NAME_METADATA: <<__rds.db_name.metadata__>>
  RDS_HOST: <<__rds.host__>>
  RDS_PORT: '<<__rds.port__>>'
