apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- ../base
- resources/kube2iam-clusterrole.yaml
- resources/kube2iam-daemonset.yaml
- resources/kube2iam-serviceaccount.yaml

patchesStrategicMerge:
- patches/ml-pipeline-viewer-template.yaml
- patches/deployment-annotations.yaml

commonAnnotations:
  iam.amazonaws.com/role: arn:aws:iam::161747956760:role/eksctl-ml-cluster-ServiceRole-18X4ZD7THSNT0
