apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: <<__s3.bucket.pipelines__>>
      keyPrefix: <<__s3.key_prefix.pipelines__>>
      endpoint: s3.amazonaws.com
      region: <<__aws_region__>>
      insecure: false
  containerRuntimeExecutor: pns
  # namespace: kubeflow
  # executorImage: gcr.io/ml-pipeline/argoexec:v2.7.5-license-compliance

