apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: kubeflow-ingressgateway-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: <<__domain__>>
  dnsNames:
    - <<__domain__>>
