apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- authorization-policy.yaml
- envoy-filter-ingressgateway-settings.yaml
- envoy-filter-oauth2-proxy.yaml
- envoy-filter-kubeflow-userid.yaml
- envoy-filter-proxy-protocol.yaml
- gateway.yaml
- peer-authentication.yaml
- request-authentication.yaml
- kubeflow-cluster-roles.yaml
