apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - deny-all-authorizationpolicy.yaml
- envoy-filter-ingressgateway-settings.yaml
- envoy-filter-kubeflow-userid.yaml
- envoy-filter-proxy-protocol.yaml
- gateway-authorizationpolicy.yaml
- kubeflow-cluster-roles.yaml
- kubeflow-gateway.yaml
# - monitoring/
