kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-s3-config
  namespace: kubeflow
data:
  REGION: <<__aws_region__>>
  BUCKET_NAME: <<__s3.bucket.pipelines__>>
  PIPELINE_FOLDER: <<__s3.path.pipelines__>>
  PIPELINE_PATH: <<__s3.path.pipelines__>>


