apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- cluster-issuer.yaml

patchesStrategicMerge:
- patches/cluster-issuer.yaml
- patches/service-account.yaml
- patches/deployment.yaml
